### ISSUE TITLE
Can you use Regex in topics to listen to events?

### ISSUE THREAD

**Issue by Anubarak** [RangerMauve/mqtt-regex#6]
Not sure if I don't understand your library or if my purpose can even be done with your libraries.

I'm not that familiar with MQTT, I just have to use it for a project. There are many topics and I need to listen to a few of them

```
foo/bar/value1
foo/bar/value2
foo/bar/value3
...
foo/bar/value80
```
I currently use your mqtt-events library, so I have one client and do
```JS
import MQTTEmitter from 'mqtt-emitter';
const events = new MQTTEmitter();

events.on('foo/bar/value1', someHandler);
events.on('foo/bar/value3', someHandler);
events.on('foo/bar/value50', someHandler);
```

I would like to use a regex and simplify those into one, for example via
```JS
events.on('foo/bar/+(value1|value3|value50)', someHandler);
```
Is that possible or even intended? Would it be possible to trigger `someHandler` only in case the 3 above emit an event?
I'm a little bit lost between your libraries and the possibilities or restrictions to be honest.

**Comment by RangerMauve** [comment]
Hey, thanks for the ping.

Hmm, the regex _could_ be possible, but it'd add a lot of complexity to this library and would likely harm performance. 😅 

It'd also make it hard to generate an MQTT event name that should actually be sent to your server to subscribe on since it'd need to be decomposed into the individual events anyway.

The current syntax stays very close to the raw [MQTT pattern spec](http://docs.sensetecnic.com/mqtt/topic-patterns/) that servers can accept, so I'd like to stick to them. If you want fancier syntax for subscribing to multiple topics at once, it's probably something you can accomplish with a library on top of mqtt-emitter.

**Comment by Anubarak** [comment]
I see. Guess I'll take what's there and use what's currently possible.
Thank you very much for your libraries and all the effort it took. As said it's the first time I use MQTT and there are all in all around 600 topics I have to subscribe to (provided by someone else) so I tought it would be better to use kinda real regex matching like PHP routers do it.

But your library and your event emitter already kinda saved my life 😂

**Comment by RangerMauve** [comment]
Glad I could help!

Sadly, with regards to topics we're limited by what the MQTT subscribe spec can do since ultimately that's what's going over the wire.

Hope your application goes well! 😁
